"""
Django settings for jacket project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v3f(_sslbnha=35#a1_pmkks!vb+h1$gy)k9b)_iwu=u9ua(@z'

# SECURITY WARNING: don't run with debug turned on in production!
#import socket
#if socket.gethostname() == 'jacket':
#    DEBUG = False
#    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
#else:
#    DEBUG = True
#    ALLOWED_HOSTS = []
DEBUG = True
ALLOWED_HOSTS = []
# DEBUG = False
# ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django_comments',
    #'django.contrib.sites',

    'DjangoUeditor',
    'hw',
    'jacket',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'jacket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'GlobalTemplates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hw.utils.bread.get_hw_zan_num',
            ],
        },
    },
]

WSGI_APPLICATION = 'jacket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
# using mysql to be the database
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'jacket',
#         'USER':'root',
#         'PASSWORD':'jacket',
#         'HOST':'127.0.0.1',
#         'PORT':'3306',
#     }
# }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC' 

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_ROOT = '/mysite/static/'
STATICFILES_DIRS = ('/mysite/static/', )
STATIC_URL = '/static/'
MEDIA_ROOT = '/mysite/media/'
MEDIA_URL = '/media/'

# 发生错误时会发送邮件给你
ADMINS = (('Jacket', 'insysujacket@gmail.com'))
SERVER_EMAIL = 'zuoyela_jacket@sina.com'
# caibudao233666

#邮件配置
EMAIL_HOST = 'smtp.sina.com'               #SMTP地址
EMAIL_PORT = 25                            #SMTP端口
EMAIL_HOST_USER = 'zuoyela_jacket@sina.com'  #我自己的邮箱
EMAIL_HOST_PASSWORD = 'caibudao233666' #我的邮箱密码
EMAIL_SUBJECT_PREFIX = u'[作业LA]'     #为邮件Subject-line前缀,默认是'[django]'
EMAIL_USE_TLS = True    #与SMTP服务器通信时，是否启动TLS链接(安全链接)。默认是false


# SITE_ID = 1
# COMMENTS_APP = 'hw'
